//
// Created by elise on 02/12/2023.
//

#ifndef PRECEDENCEETTEMPSCYCLE_TEMPSCYCLE_H
#define PRECEDENCEETTEMPSCYCLE_TEMPSCYCLE_H

double readTempsCycle();

#endif //PRECEDENCEETTEMPSCYCLE_TEMPSCYCLE_H
